name: S3 Snapshot Workflow

on:
  repository_dispatch:
    types: [snapshot-event]
jobs:
  process-snapshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Snapshot from S3
      run: |
        curl -o snapshot.zip '${{ github.event.client_payload.signedURL }}'

    - name: Unzip Snapshot
      run: unzip -o snapshot.zip -d snapshot
      
    - name: Clean up existing zip files
      run: |
          echo "Removing existing zip files..."
          rm -f *.zip || true  # The || true ensures that this command doesn't fail the workflow if no zip files are found
        
    - name: Create New Branch and Push
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        git config --global user.email "you.zouhairi@gmail.com"
        git config --global user.name "YussefZ"
        git checkout -b update-main-for-snapshot-delete-${{ github.event.client_payload.id }}
        # This is to ensure the directory exists and should be deleted
        if [ -d snapshot ]; then
          rm -rf snapshot
          git add -A
          git commit -m "Prepare to delete snapshot directory"
          git push --set-upstream origin update-main-for-snapshot-delete-${{ github.event.client_payload.id }}
          echo "Snapshot directory prepared for deletion."
        else
          echo "Snapshot directory does not exist on this branch."
        fi

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh

    - name: Create Pull Request for Deletion
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        # Only create a PR if there were changes (i.e., snapshot directory existed and was deleted)
        if git diff --exit-code --quiet; then
          echo "No changes to push. Snapshot directory did not exist."
        else
          gh pr create --base main --head update-main-for-snapshot-delete-${{ github.event.client_payload.id }} --title "Delete snapshot directory" --body "Automated deletion of snapshot directory."
        fi

    - name: Auto-Merge Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        PR_NUMBER=$(gh pr list --base main --head update-main-for-snapshot-delete-${{ github.event.client_payload.id }} --json number --jq '.[0].number')
        if [ ! -z "$PR_NUMBER" ]; then
          gh pr merge "$PR_NUMBER" --auto --merge
        else
          echo "PR not found or cannot be merged automatically."
        fi
