name: S3 Snapshot Workflow

on:
  repository_dispatch:
    types: [snapshot-event]
jobs:
  process-snapshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Snapshot from S3
      run: |
        curl -o snapshot.zip '${{ github.event.client_payload.signedURL }}'

    - name: Unzip Snapshot
      run: unzip -o snapshot.zip -d snapshot
      
    - name: Clean up existing zip files
      run: |
          echo "Removing existing zip files..."
          rm -f *.zip || true  # The || true ensures that this command doesn't fail the workflow if no zip files are found
        
    - name: Create New Branch and Push
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        git config --global user.email "you.zouhairi@gmail.com"
        git config --global user.name "YussefZ"
        git checkout -b new-branch-${{ github.event.client_payload.id }}
        git add .
        git commit -m "Add new snapshot"
        # Including the PAT in the repository URL for authentication
        echo "Setting remote URL with PAT..."
        git remote set-url origin https://x-access-token:${REPO_ACCESS_TOKEN}@github.com/Yussefz/snapshot-release.git
        echo "Attempting to push to the repository..."
        git push --set-upstream origin new-branch-${{ github.event.client_payload.id }}  
        
    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        gh pr create --base main --head new-branch-${{ github.event.client_payload.id }} --title "Merge new snapshot" --body "Automated snapshot merge"

    - name: Auto-Merge Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        PR_NUMBER=$(gh pr list --base main --head new-branch-${{ github.event.client_payload.id }} --json number --jq '.[0].number')
        if [ ! -z "$PR_NUMBER" ]; then
          gh pr merge "$PR_NUMBER" --auto --merge
        else
          echo "PR not found or cannot be merged automatically."
        fi
