name: S3 Snapshot Workflow

on:
  repository_dispatch:
    types: [snapshot-event]
jobs:
  process-snapshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Snapshot from S3
      run: |
        curl -o snapshot.zip '${{ github.event.client_payload.signedURL }}'

    - name: Unzip Snapshot
      run: unzip snapshot.zip -d snapshot
      
    - name: Debug Environment Variables
      run: |
        echo "Checking if environment variables are set..."
        if [ -z "${REPO_ACCESS_TOKEN}" ]; then
          echo "REPO_ACCESS_TOKEN is not set."
        else
          echo "REPO_ACCESS_TOKEN is set."
        fi
        
    - name: Create New Branch
      run: |
        git checkout -b new-branch-${{ github.event.client_payload.id }}
        git add .
        git config --global user.email "you.zouhairi@gmail.com"
        git config --global user.name "YussefZ"
        git commit -m "Add new snapshot"
        git push origin new-branch-${{ github.event.client_payload.id }}
      env:
        GIT_AUTHOR_EMAIL: you.zouhairi@gmail.com
        GIT_AUTHOR_NAME: YussefZ
        GIT_COMMITTER_EMAIL: you.zouhairi@gmail.com
        GIT_COMMITTER_NAME: YussefZ
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}    
