name: S3 Snapshot Workflow

on:
  repository_dispatch:
    types: [snapshot-event]
jobs:
  process-snapshot:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Snapshot from S3
      run: |
        curl -o snapshot.zip '${{ github.event.client_payload.signedURL }}'

    - name: Unzip Snapshot
      run: unzip snapshot.zip -d snapshot
      
    - name: Debug Environment Variables
      run: |
        echo "Checking if environment variables are set..."
        if [ -z "${{ secrets.REPO_ACCESS_TOKEN }}" ]; then
          echo "REPO_ACCESS_TOKEN is not set."
        else
          echo "REPO_ACCESS_TOKEN is set."
        fi
        
    - name: Create New Branch and Push
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        git config --global user.email "you.zouhairi@gmail.com"
        git config --global user.name "YussefZ"
        git checkout -b new-branch-${{ github.event.client_payload.id }}
        git add .
        git commit -m "Add new snapshot"
        git remote add origin https://github.com/Yussefz/snapshot-release.git
        # Including the PAT in the repository URL for authentication
        git remote set-url origin https://x-access-token:${REPO_ACCESS_TOKEN}@github.com/Yussefz/snapshot-release.git
        git push --set-upstream origin new-branch-${{ github.event.client_payload.id }}   
